### ISSUE TITLE
Abstract the replaceing part

### ISSUE THREAD

**Issue by maraisr** [JasonEtco/readme-box#1]
Hey mate, great tool this!

I'm actually looking for something like this. Just not specifically related to readme's. So was wondering, how would you feel about potentially abstracting the replacing part, so that I can feed it raw markdown, and have the _block replaced_, that you could then also use for the readme fetching. 

I'm trying to use this to update sections of a PR description. So sure, your regex function is enough, but would rather someone maintain it ;)

Cheers though man, this is a great thing!

**Comment by JasonEtco** [comment]
Hey @maraisr 👋 thanks for the kind words 😊 

Ideally, I'd love to support what you're describing. I _think_ that should already be possible - I tried to make that clear in the README, but let me know if this makes sense:

```js
// Get the contents of a section of the provided string. `content` is just a regular markdown string
const sectionContents = box.getSection('example-section', content)

// Return a string with the replaced contents. This returns a string!
const replacedContents = box.replaceSection({
  section: 'example-section',
  oldContent,
  newContent
})
```

If you [look at the source for `ReadmeBox.updateSection`](https://github.com/JasonEtco/readme-box/blob/c6bbebfa198297297128e58e04b053559d8cb439/src/index.ts#L41-L61), it calls the above methods to do the same block replacing that you're asking about. Hope that makes sense!

As for moving that functionality entirely to a different library - I don't think I'll be doing that, it just feels too specific to me to be useful. That said, you're welcome to copy-paste the code and publish such a library!
