### ISSUE TITLE
no-op if contents unchanged?

### ISSUE THREAD

**Issue by sw-yx** [JasonEtco/readme-box#3]
hey Jason nice library!

i would like this to no-op if contents are unchanged, this avoids spurious commits. would that be supported?

shawn

**Comment by JasonEtco** [comment]
That's a great question! I'm not sure - I can see a "spurious commit" being useful, but I also see why that'd be annoying. Right now, it _will replace_ the contents, regardless of whether or not anything has changed. We could change that; I think a `ReadmeBox#needsUpdating` private method would make sense. It'd do something naive like a strict equality check:

```ts
class ReadmeBox {
  private needsUpdating (section: string, baseContent: string, newContents: string): boolean {
    const oldContents = this.getSection(section, baseContent)
    return oldContents !== newContents
  }
}
```

I'd definitely want an `allowNoOps` or `ignoreNoOps` option or something, to still commit even if there are no changes. I can see this being a little flaky.

**Comment by sw-yx** [comment]
ya thats what i have now: https://github.com/sw-yx/sw-yx/blob/master/scrape.js#L29

i basically just dont want to wreck the commit history if i set this on a frequent cronjob y know

**Comment by gr2m** [comment]
I get tons of empty commits like this: https://github.com/gr2m/helpdesk/commit/886c35c804e106dbf21b73c1948fa28c46d68964. 

As empty commits is the current behavior, maybe it would be better to implement a `ignoreNoOps` option? Or create an option `emptyCommits` and set it to true by default for now, then change the default in a future breaking version?

Let me know and I'll create a pull request

**Comment by JasonEtco** [comment]
> Or create an option emptyCommits and set it to true by default for now, then change the default in a future breaking version?

I like that @gr2m! If you want to open a PR adding the option/behavior that'd be great, and I'll handle the release and flipping the default for a major version bump.
